version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      typeorm:
        patterns:
          - 'typeorm'
          - '@nestjs/typeorm'
          - 'pg'
      auth:
        patterns:
          - 'passport'
          - 'passport-*'
          - '@nestjs/jwt'
          - '@nestjs/passport'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - '@typescript-eslint/*'
      jest:
        patterns:
          - 'jest'
          - '@types/jest'
          - 'ts-jest'
          - 'supertest'
          - '@nestjs/testing'
      redis:
        patterns:
          - 'redis'
          - 'ioredis'
          - 'cache-manager*'
          - 'bullmq'
          - '@nestjs/bullmq'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
